#104 reorganize code
Marine-Sanson/ocprojet5 pull request #105
Opened 2023-08-23 15:19 UTC by Marine-Sanson

Change AbstractManager to singleton DatabaseService.
Reorganize the code adding services and mapper.
Move the User into Entities and create a Model. Use this model to manage connection.
Remove index functions in the controllers.

2023-08-25 08:05 UTC, antoinetrouve requested changes

2023-08-25 08:05 UTC, antoinetrouve commented on index.php
>      if(!isset($_SESSION["connected"]))
Ici tu pourrais faire une fonction ou un service qui gère ta Session.

2023-08-25 08:05 UTC, antoinetrouve commented on src/entity/UserEntity.php
> +        public ?int $id, public string $name, public string $firstName,
tout doit etre a la ligne. Bizarre que ton editeur ou ton linter te laisse faire çà...

2023-08-25 08:05 UTC, antoinetrouve commented on src/mapper/Usermapper.php
> +    public function changeUserToConnection(UserEntity $user) :ConnectionModel
```suggestion
    public function transformToUserConnectionModel(UserEntity $user): UserConnectionModel
```

2023-08-25 08:05 UTC, antoinetrouve commented on src/mapper/Usermapper.php
> +        $connectionModel = new ConnectionModel(
```suggestion
        return new ConnectionModel(
```

2023-08-25 08:05 UTC, antoinetrouve commented on src/model/ConnectionModel.php
> +class ConnectionModel
```suggestion
class UserConnectionModel
```

Eventuellement tu peux enlever le suffixe Model puisque l'on sait que tu es dans le dossier model

2023-08-25 08:05 UTC, antoinetrouve commented on src/model/ConnectionModel.php
> +        public string $firstName, public string $username,
Tout à la ligne

2023-08-25 08:05 UTC, antoinetrouve commented on index.php
>      if(!isset($_SESSION["connected"]))
regarde cette interface et cette classe comme exemple : 
https://dev.to/fadymr/php-create-a-simple-session-wrapper-class-dpk

2023-08-25 08:05 UTC, antoinetrouve commented on src/entity/UserEntity.php
> +        $this->id = $id;
normalement tu n'as plus besoin de faire ceci en mettant `public string $username`

2023-08-25 08:05 UTC, antoinetrouve commented on src/model/ConnectionModel.php
> +        $this->firstName = $firstName;
Idem ici. En PHP 8.1 il me semble que lorsque tu déclares en propriété `public string $firsname` tu n'as plus besoin d'attribué ta variable $this->firstname. C'est fait automatiquement.

2023-08-25 08:05 UTC, antoinetrouve commented on src/service/Router.php
> +            if ($_POST === []) {
un petit match()

2023-08-25 08:05 UTC, antoinetrouve commented on src/service/UserService.php
> +        $result = $userRepository->getUser($username);
tu n'as pas réussi à utiliser autre chose que le FETCH_ASSOC dans ta requete SQL ? ca serait bien que ton repository te renvois un UserEntity plutot qu'un tableau de résultat.

2023-08-25 08:05 UTC, antoinetrouve commented on src/service/UserService.php
> +        if ($username === "" || $password === "") {
tu peux faire un early return 
```suggestion
        if ($username === "" || $password === "") return false;
        return true; // pas besoin de else ici.
```

2023-08-25 08:05 UTC, antoinetrouve commented on src/service/UserService.php
> +class UserService
il te manque le singleton. getInstance()

2023-08-25 09:03 UTC, Marine-Sanson commented on src/entity/UserEntity.php
> +        public ?int $id, public string $name, public string $firstName,
corrigé

2023-08-25 09:05 UTC, Marine-Sanson commented on src/mapper/Usermapper.php
> +    public function changeUserToConnection(UserEntity $user) :ConnectionModel
corrigé

2023-08-25 09:10 UTC, Marine-Sanson commented on src/mapper/Usermapper.php
> +        $connectionModel = new ConnectionModel(
corrigé

2023-08-25 09:12 UTC, Marine-Sanson commented on src/model/ConnectionModel.php
> +        $this->firstName = $firstName;
oui tu as raison. Corrigé

2023-08-25 09:15 UTC, Marine-Sanson commented on src/service/UserService.php
> +        if ($username === "" || $password === "") {
corrigé

2023-08-25 09:16 UTC, Marine-Sanson commented on src/model/ConnectionModel.php
> +class ConnectionModel
Corrigé. Je préfère garder Model quand même

2023-09-05 07:36 UTC, Marine-Sanson commented on src/service/UserService.php
> +class UserService
ok fait

2023-09-05 14:51 UTC, Marine-Sanson commented on src/service/UserService.php
> +        if ($username === "" || $password === "") {
En fait je rechange parce que la syntaxe en une seule ligne est mise en warning par codesniffer

2023-09-06 13:24 UTC, Marine-Sanson commented on index.php
>      if(!isset($_SESSION["connected"]))
ok fait

2023-09-06 13:49 UTC, antoinetrouve commented on src/controller/UserController.php
> +        $session->set("connected", false);
je pense que c'est ici le problème. Tu destroy la session à la déconnexion mais en fait tu en as besoins juste après.

2023-09-06 13:49 UTC, antoinetrouve commented on src/controller/UserController.php
> +        $session->destroy();
```suggestion
```

2023-09-06 13:49 UTC, antoinetrouve commented on src/controller/UserController.php
> +        $session->set("button", "connect");
je ne comprends pas pourquoi tu as besoin d'avoir dans ta session le "bouton". L'affichage du bouton devrait etre lié à la variable "connected" qu'il y a dans ta session. Et tu gères la visibilité du bouton dans ton twig.

2023-09-06 13:49 UTC, antoinetrouve commented on src/mapper/Usermapper.php
> + * UserMapper File Doc Comment
revoir le nom du fichier php UserMapper

2023-09-06 13:49 UTC, antoinetrouve commented on src/service/SessionService.php
> +            session_start();
j'éviterais de faire un session_start. Celà voudrait dire qu'a chaque fois que tu fais un getInstance tu créés une session.

Tu devrais plutot avoit une fonction `start()` qui start la session et une autre `getSession()` qui retourne $_session

2023-09-06 13:49 UTC, antoinetrouve commented on src/service/UserService.php
> +            $session->remove("connected");
```suggestion
            $session->remove(SessionService::CONNECTED);
```

2023-09-06 13:49 UTC, antoinetrouve commented on src/service/UserService.php
> +            $session->set("user", $userData);
```suggestion
            $session->setUser($userData);
```

2023-09-06 13:49 UTC, antoinetrouve commented on src/service/UserService.php
> +            $session->set("user", $userData);
`public function setUser(UserSession $userSession): void`

$this->session[SessionService::USER] = $userSession->toArray()

`public function toArray() : arrray`
return [
     "first_name" = $this->firstName,
     ........
]

2023-09-08 07:18 UTC, Marine-Sanson commented on src/controller/UserController.php
> +        $session->set("connected", false);
ok fait

2023-09-08 07:18 UTC, Marine-Sanson commented on src/controller/UserController.php
> +        $session->set("button", "connect");
modifié

2023-09-08 08:09 UTC, Marine-Sanson commented on src/service/SessionService.php
> +            session_start();
ok fait

2023-09-08 08:09 UTC, Marine-Sanson commented on src/controller/UserController.php
> +        $session->destroy();
ok fait

2023-09-08 08:14 UTC, merged