Feature/#40 to #50 add posts comments
Marine-Sanson/ocprojet5 pull request #138
Opened 2023-09-27 14:24 UTC by Marine-Sanson

2023-09-27 14:58 UTC, antoinetrouve requested changes

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/CommentController.php
> +    private $_commentRepository;
c'est un service qui doit etre dans le controller pas un repository
`controler - service - repository `
```suggestion
    private CommentService $_commentService;
```

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/CommentController.php
> +
ligne superflue

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/CommentController.php
> +        $this->_commentRepository = new CommentRepository();
```suggestion
        $this->_commentService = CommentService::getInstance();
```

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/CommentController.php
> +    public static function getInstance() :CommentController
```suggestion
    public static function getInstance(): CommentController
```

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/CommentController.php
> +    public function __construct()
```suggestion
    private function __construct()
```

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/CommentController.php
> +    public function getOnePostComments(int $postId) :array
A déplacer dans le commentService.php

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/CommentController.php
> +
ligne superflue

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +use App\entity\CommentEntity;
ton controller ne doit pas connaitre CommentEntity qui est un model dédié à la base de données. Donc seul le repository et éventuellement le service ont accès à ce model.

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +    private $_postService;
```suggestion
    private PostService $_postService;
```

Attention PHP 8 ! on type les variables en Php.

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +    private $_commentService;
PHP 8

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +    public function __construct(public TemplateInterface $template)
```suggestion
    private function __construct(public TemplateInterface $template)
```

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +    public function showPostDetails(int $postId) :void
```suggestion
    public function showPostDetails(int $postId): void
```

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +        if (isset($_POST["action"])) {
```suggestion
        if (isset($_POST["action"] && $_POST["action"] === $this->_commentService::ACTION)) {
```

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +            if ($_POST["action"] === $this->_commentService::ACTION) {
```suggestion

```

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +                if ($isSubmitted && $isValid) {
```suggestion
                if ($this->isSubmitted($this->_commentService::ACTION) && $this->isValid($_POST)) {
```

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +                $isSubmitted = $this->isSubmitted($this->_commentService::ACTION);
```suggestion
                
```

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +                $isValid = $this->isValid($_POST);
```suggestion
                
```

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +        if (isset($_POST["action"])) {
Essais de voir pour faire un minimum de if else imbriqué. Peut être utiliser la methode `match` de php 8 ?

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +        $postDetails = $this->_postService->getPostDetails($postId);
Pourquoi PostDetails est un tableau et non un objet ?

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +                'id' => $postId,
```suggestion
                'id' => $postDetails->getPostId() ....
```
Avec un objet celà serait mieux.

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +                'comments' => $postDetails["comments"],
```suggestion
                'comments' => $postDetails->getComments(),
```

2023-09-27 14:58 UTC, antoinetrouve commented on src/controller/PostController.php
> +    public function validCommentForm(CommentEntity $comment) :CommentEntity
On ne dervait pas avoir de notion de Entity dans un controller.

2023-09-27 14:58 UTC, antoinetrouve commented on src/model/UserConnectionModel.php
> +
ligne superflue

2023-09-27 14:58 UTC, antoinetrouve commented on src/repository/CommentRepository.php
> +        $id_post = $newComment->id_post;
inutile de faire des variables, tu peux directement mettre l'appelle à la variable dans ton tableau parameters

2023-09-27 14:58 UTC, antoinetrouve commented on src/repository/CommentRepository.php
> +        $this->_db = DatabaseService::getInstance();
Mettre plutot cette ligne dans le constructeur afin de n'appeler l'instance de Database q'une seule fois.

2023-09-27 14:58 UTC, antoinetrouve commented on src/repository/UserRepository.php
> +        $this->_db = DatabaseService::getInstance();
mettre ceci dans le constructeur.

2023-09-27 14:58 UTC, antoinetrouve commented on src/repository/UserRepository.php
> +        $id = $this->_db->execute($request, $parameters);
utilise la methode fetch plutot que execute pour récupérer un seul résultat et non un tableau de résultat. De sorte que tu n'ai pas besoin de faire $id[0] 

https://www.php.net/manual/en/pdostatement.fetch.php

2023-09-27 14:58 UTC, antoinetrouve commented on src/service/CommentService.php
> +use App\controller\CommentController;
Pourquoi ton service à la notion de controller dedans ? Sa ne dervait pas : 

Controler - Service - Repository

2023-09-27 14:58 UTC, antoinetrouve commented on src/service/CommentService.php
> +    private $_commentRepository;
PHP 8 et POO

2023-09-27 14:58 UTC, antoinetrouve commented on src/service/CommentService.php
> +        $this->_commentRepository = new CommentRepository();
```suggestion
        $this->_commentRepository = CommentRepository::getInstance();
```

2023-09-27 14:58 UTC, antoinetrouve commented on src/service/CommentService.php
> +    public function manageComment() :CommentEntity
```suggestion
    public function manageComment(string $username, int $postId, string $content) :CommentEntity
```

2023-09-27 14:58 UTC, antoinetrouve commented on src/service/CommentService.php
> +            $id_user = $userService->getUserId($_POST["username"]);
attention seul ton controller doit accéder au variable POST qui est lié à un formulaire donc à la vue. (Modèle MVC)

```suggestion
            $id_user = $userService->getUserId($username);
```

2023-09-27 14:58 UTC, antoinetrouve commented on src/service/CommentService.php
> +            $postId = intval($_POST["postId"]);
idem

2023-09-27 14:58 UTC, antoinetrouve commented on src/service/CommentService.php
> +            $comment = new CommentEntity(null, $postId, $id_user, $_POST["content"], $currentDate, $currentDate, false);
idem pour la variable POST

2023-09-27 15:40 UTC, Marine-Sanson commented on src/controller/CommentController.php
> +    public static function getInstance() :CommentController
ho ben mince j'ai fait ça partout !!!

2023-09-27 15:40 UTC, Marine-Sanson commented on src/controller/CommentController.php
> +    private $_commentRepository;
ok fait

2023-09-27 15:40 UTC, Marine-Sanson commented on src/controller/CommentController.php
> +
ok fait

2023-09-27 15:41 UTC, Marine-Sanson commented on src/controller/CommentController.php
> +        $this->_commentRepository = new CommentRepository();
ok fait

2023-09-27 15:41 UTC, Marine-Sanson commented on src/controller/CommentController.php
> +    public function __construct()
ok fait

2023-09-27 15:48 UTC, Marine-Sanson commented on src/service/CommentService.php
> +        $this->_commentRepository = new CommentRepository();
ok fait

2023-09-27 15:51 UTC, Marine-Sanson commented on src/service/CommentService.php
> +    public function manageComment() :CommentEntity
ok fait

2023-09-27 15:54 UTC, Marine-Sanson commented on src/service/CommentService.php
> +            $id_user = $userService->getUserId($_POST["username"]);
ok fait

2023-09-27 15:55 UTC, Marine-Sanson commented on src/service/CommentService.php
> +            $postId = intval($_POST["postId"]);
fait

2023-09-27 15:55 UTC, Marine-Sanson commented on src/service/CommentService.php
> +            $comment = new CommentEntity(null, $postId, $id_user, $_POST["content"], $currentDate, $currentDate, false);
fait

2023-09-27 16:00 UTC, Marine-Sanson commented on src/controller/PostController.php
> +    public function showPostDetails(int $postId) :void
aie aie aie je vais changer ça partout...

2023-09-27 16:40 UTC, Marine-Sanson commented on src/controller/CommentController.php
> +    public function getOnePostComments(int $postId) :array
fait

2023-09-27 16:40 UTC, Marine-Sanson commented on src/controller/CommentController.php
> +
fait

2023-09-28 06:51 UTC, Marine-Sanson commented on src/controller/PostController.php
> +    private $_commentService;
fait

2023-09-28 06:56 UTC, Marine-Sanson commented on src/controller/PostController.php
> +use App\entity\CommentEntity;
ok fait

2023-09-28 06:56 UTC, Marine-Sanson commented on src/controller/PostController.php
> +    private $_postService;
fait

2023-09-28 07:20 UTC, Marine-Sanson commented on src/controller/PostController.php
> +    public function __construct(public TemplateInterface $template)
ok fait

2023-09-28 07:26 UTC, Marine-Sanson commented on src/controller/PostController.php
> +        if (isset($_POST["action"])) {
ok fait

2023-09-28 07:26 UTC, Marine-Sanson commented on src/controller/PostController.php
> +            if ($_POST["action"] === $this->_commentService::ACTION) {
fait

2023-09-28 07:26 UTC, Marine-Sanson commented on src/controller/PostController.php
> +                if ($isSubmitted && $isValid) {
ok fait

2023-09-28 07:26 UTC, Marine-Sanson commented on src/controller/PostController.php
> +                $isSubmitted = $this->isSubmitted($this->_commentService::ACTION);
fait

2023-09-28 07:27 UTC, Marine-Sanson commented on src/controller/PostController.php
> +                $isValid = $this->isValid($_POST);
fait aussi

2023-09-28 07:28 UTC, Marine-Sanson commented on src/controller/PostController.php
> +    public function validCommentForm(CommentEntity $comment) :CommentEntity
ok fait

2023-09-28 07:29 UTC, Marine-Sanson commented on src/model/UserConnectionModel.php
> +
ok

2023-09-28 08:01 UTC, Marine-Sanson commented on src/repository/CommentRepository.php
> +        $id_post = $newComment->id_post;
ok fait

2023-09-28 08:01 UTC, Marine-Sanson commented on src/repository/CommentRepository.php
> +        $this->_db = DatabaseService::getInstance();
ok fait

2023-09-28 08:02 UTC, Marine-Sanson commented on src/repository/UserRepository.php
> +        $this->_db = DatabaseService::getInstance();
fait aussi

2023-09-28 08:04 UTC, Marine-Sanson commented on src/service/CommentService.php
> +use App\controller\CommentController;
ok enlevé

2023-09-28 08:04 UTC, Marine-Sanson commented on src/service/CommentService.php
> +    private $_commentRepository;
ok

2023-09-28 09:04 UTC, Marine-Sanson commented on src/controller/CommentController.php
> +    public function getOnePostComments(int $postId) :array
fait

2023-09-29 07:51 UTC, Marine-Sanson commented on src/controller/PostController.php
> +        $postDetails = $this->_postService->getPostDetails($postId);
ok fait

2023-09-29 07:52 UTC, Marine-Sanson commented on src/controller/PostController.php
> +                'id' => $postId,
fait

2023-09-29 07:53 UTC, Marine-Sanson commented on src/controller/PostController.php
> +                'comments' => $postDetails["comments"],
fait mais reste un truc bizarre.. $postDetails->comments() fonctionne mais pas $postDetails->getComments()...

2023-09-29 10:04 UTC, antoinetrouve requested changes
Supprimer la notion de template dans les services. Un template ca fait partie de la vue et donc ne doit etre accessible et utilisé que par le controller et éventuellement le router.

2023-09-29 10:04 UTC, antoinetrouve commented on src/controller/AbstractController.php
> +        $data = html_entity_decode($data);
```suggestion
        return htmlspecialchars_decode(html_entity_decode($data));
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/controller/AbstractController.php
>          $data = stripslashes($data);
```suggestion
        return stripslashes(trim($data));
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/controller/CommentController.php
> +        $this->_commentService = new CommentService();
```suggestion
        $this->_commentService = CommentService::getInstance();
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/controller/CommentController.php
> +    public function getOnePostComments(int $postId): array
```suggestion
    public function DisplayPostComments(int $postId): array
```

Je me demande pourquoi tu as une fonction dans ton controller qui ne retourne pas une vue...

2023-09-29 10:04 UTC, antoinetrouve commented on src/controller/PostController.php
> +    private function __construct(public TemplateInterface $template)
```suggestion
    private function __construct(private readonly TemplateInterface $template)
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/controller/PostController.php
> +        foreach ($postDetails->getComments() as $postCom) {
moi je ferais cette partie de setComments dans un service. Dans l'ideal quand tu fais un getPostDetails tu as déjà tous les éléments.

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/CommentService.php
> +    public TemplateInterface $template;
```suggestion

```

Un service n'a pas accès à la vue :)

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/CommentService.php
> +    public function __construct()
```suggestion
    private function __construct()
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/CommentService.php
> +        $comments = $this->_commentRepository->getOnePostComments($postId);
```suggestion
        return $this->_commentRepository->getOnePostComments($postId);
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/CommentService.php
> +            $id_user = $userService->getUserId($username);
```suggestion
            $userId = $userService->getUserId($username);
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/CommentService.php
> +            $comment = new CommentEntity(null, $postId, $id_user, $content, $currentDate, $currentDate, false);
```suggestion
            return new CommentEntity(null, $postId, $id_user, $content, $currentDate, $currentDate, false);
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/CommentService.php
> +    public function createNewComment(CommentEntity $validateComment)
```suggestion
    public function createNewComment(CommentEntity $validateComment): array
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/CommentService.php
> +        $createNewComment = $this->_commentRepository->insertComment($validateComment);
Si le retour de ta fonction insertComment est un boolean :
```suggestion
        $isCommentCreated = $this->_commentRepository->insertComment($validateComment);
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/PostService.php
> +    public TemplateInterface $template;
```suggestion

```

Pas de vue ici. Seul ton Controller est dépendant de ton moteur de template.

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/PostService.php
> +        $this->_postRepository = new PostRepository();
```suggestion
        $this->_postRepository = PostRepository::getInstance();
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/PostService.php
> +    public function __construct()
```suggestion
    private function __construct()
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/PostService.php
> +        $posts = $postmapper->transformToListOfPostModel($results);
```suggestion
        $posts = (PostsMapper::getInstance())->transformToListOfPostModel($results);
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/PostService.php
> +        $postmapper = new PostsMapper();
```suggestion

```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/PostService.php
> +    private function _getPostData(int $postId): array // dans le postService
```suggestion
    private function _getPostData(int $postId): array
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/PostService.php
> +        $post = $this->_postRepository->getOnePostData($postId);
```suggestion
        return $this->_postRepository->getOnePostData($postId);
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/PostService.php
> +        $comments = $this->_commentService->getComments($postId);
```suggestion
        return $this->_commentService->getComments($postId);
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/PostService.php
> +        $commentRepository = new CommentRepository();
```suggestion
        $commentRepository = CommentRepository::getInstance();
```
Il serait judicieux d'ajouter le `CommentRepository::getInstance()` dans le constructeur, idem pour les mapper

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/PostService.php
> +        if (isset($id)) {
Avec un early return : 

```suggestion
        if (!isset($id)) { return false }
        return true
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/Router.php
> +                    $postController->showPostDetails($id);
```suggestion
                    $postController->showPostDetails($route["param"]);
```

2023-09-29 10:04 UTC, antoinetrouve commented on src/service/UserService.php
> +        $userId = $this->_userRepository->getUserId($username);
```suggestion
        return $this->_userRepository->getUserId($username);
```

2023-09-29 14:08 UTC, Marine-Sanson commented on src/controller/CommentController.php
> +    public function getOnePostComments(int $postId): array
c'est le PostController qui va utiliser cette fonction du CommentsController pour récupérer les commentaires et les utiliser pour retourner la vue. Je vais déplacer cette fonction dans le Comment Service

2023-09-29 14:17 UTC, Marine-Sanson commented on src/service/CommentService.php
> +    public TemplateInterface $template;
En plus il ne sert plus à rien

2023-09-29 14:18 UTC, Marine-Sanson commented on src/service/CommentService.php
> +    public function __construct()
fait

2023-09-29 14:19 UTC, Marine-Sanson commented on src/service/CommentService.php
> +        $comments = $this->_commentRepository->getOnePostComments($postId);
ok

2023-09-29 14:20 UTC, Marine-Sanson commented on src/service/CommentService.php
> +            $id_user = $userService->getUserId($username);
ok

2023-09-29 14:21 UTC, Marine-Sanson commented on src/service/CommentService.php
> +            $comment = new CommentEntity(null, $postId, $id_user, $content, $currentDate, $currentDate, false);
fait

2023-09-29 14:22 UTC, Marine-Sanson commented on src/service/CommentService.php
> +    public function createNewComment(CommentEntity $validateComment)
oups

2023-09-29 14:32 UTC, Marine-Sanson commented on src/service/PostService.php
> +        $this->_postRepository = new PostRepository();
ok

2023-09-29 14:32 UTC, Marine-Sanson commented on src/service/PostService.php
> +    public function __construct()
ok

2023-09-29 14:38 UTC, Marine-Sanson commented on src/service/PostService.php
> +        $posts = $postmapper->transformToListOfPostModel($results);
fait

2023-09-29 14:39 UTC, Marine-Sanson commented on src/service/PostService.php
> +        $postmapper = new PostsMapper();
ok

2023-09-29 14:39 UTC, Marine-Sanson commented on src/service/PostService.php
> +    private function _getPostData(int $postId): array // dans le postService
ok

2023-09-29 14:41 UTC, Marine-Sanson commented on src/service/PostService.php
> +        $post = $this->_postRepository->getOnePostData($postId);
fait

2023-09-29 14:50 UTC, Marine-Sanson commented on src/service/PostService.php
> +        $commentRepository = new CommentRepository();
ok fait

2023-09-29 14:55 UTC, Marine-Sanson commented on src/service/PostService.php
> +        if (isset($id)) {
ok fait mais code sniffer n'aime pas...

2023-09-29 14:56 UTC, Marine-Sanson commented on src/service/Router.php
> +                    $postController->showPostDetails($id);
ok fait

2023-09-29 14:57 UTC, Marine-Sanson commented on src/service/UserService.php
> +        $userId = $this->_userRepository->getUserId($username);
fait

2023-09-29 14:58 UTC, Marine-Sanson commented on src/service/PostService.php
> +        $comments = $this->_commentService->getComments($postId);
fait

2023-09-29 14:59 UTC, Marine-Sanson commented on src/service/PostService.php
> +    public TemplateInterface $template;
ok

2023-09-29 15:00 UTC, Marine-Sanson commented on src/service/CommentService.php
> +        $createNewComment = $this->_commentRepository->insertComment($validateComment);
ce n'est pas le cas

2023-10-02 06:51 UTC, Marine-Sanson commented on src/controller/PostController.php
> +        foreach ($postDetails->getComments() as $postCom) {
a voir plus tard, refacto

2023-10-02 07:11 UTC, merged