Tech/1234 install composer and more
Marine-Sanson/ocprojet5 pull request #73
Opened 2023-08-01 12:11 UTC by Marine-Sanson

première pull request

2023-08-01 15:07 UTC, Marine-Sanson commented
With a class Demo in src\Demo to test autoload,
With a template index.html to test Twig,
And css classes in the index to test Bootstrap
For the moment no Sass, I'll see after if I use it or not in this project

2023-08-02 07:39 UTC, antoinetrouve requested changes
Il faut juste modifier ta configuration git pour y ajouter l'option.

2023-08-02 07:39 UTC, antoinetrouve commented on .gitignore
> +/vendor
Attention, voir si tu peux mettre par defaut à la fin de ton fichier une ligne vide. C'est une option dans ton .gitconfig (https://www.gloomycorner.com/line-ending-configuration-in-git/)

`$ git config core.autocrlf input`

2023-08-02 07:39 UTC, antoinetrouve commented on src/Demo/Test.php
> +class Test {
Je ne pense pas que tu utilises cette classe. Tu peux la supprimer.

2023-08-02 07:48 UTC, antoinetrouve commented
La description de ta PR doit etre sur ta PR mais pas dans un commentaire ;) (en éditant ta PR)

2023-08-02 08:31 UTC, Marine-Sanson commented on .gitignore
> +/vendor
ok fait

2023-08-02 08:31 UTC, Marine-Sanson commented on src/Demo/Test.php
> +class Test {
ok fait

2023-08-02 08:46 UTC, merged